---
all:
  vars:
    net_gateway: 10.1.0.1
    net_dns_server: 10.1.0.1
    net_subnet_mask: /16
  children:
    vms:
      hosts:
        centos_vm1:
          ansible_host: 10.1.200.1
          ansible_user: root
          vm_mac_address: "52:54:00:11:22:01"
          vm_uuid: df3f3180-ec74-4a0c-a995-d2e5a2b97c23  
        centos_vm2:
          ansible_host: 10.1.200.2
          ansible_user: root
          vm_mac_address: "52:54:00:11:22:02"
          vm_uuid: df3f3180-ec74-4a0c-a995-d2e5a2b97c24  
      vars:
        vm_root_ssh_auth_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCf4LXC+qylproRIHX+AZXxWgoadV0J1xHGqOXBKNzI0dVm0Uq9VrtKBBEkqIMREoj//dMvvHw4TBpZEyuCvrepqIkoENczfGsfyCLILj7LJ+xwLKCGJ/I01zGVIBY1HfgbQilHHumo8SjGqI5GjZkgoKQ8r7bxbUMc7X25YrdKehsU/wtjoWySiJ0bGeSolpMqt4cExsz/jwweLGCv3lDJ/bpZDnSl2ab9OaiSLg+udSBj9nprlCW7jBzGvm2uFfomXYN4Su+iVvfDgLbkKa5BqD32Jsy27pYx275IDP3Rkzq7MfklCuNHloWb2IAMU67Wc8Lt8NC2MfrymhBzXWOiz4gMF09QBWP/mkflVzsllyeAz5cZU1HEYKwRtaCDpcubEsHG1Pk7mw5eAMT0pp3L66cBfHTT4xWXXFAdAm/blZnvPNUa+w3DG/F6nP+Q6HHIXQ9+S8fEMxgwFpIc/ZuKGKwhb9gxsbKVp57r07DGcR5cLtPkgEudmWUsch4PSSk= danny@chunkypb"
        vm_root_pass: pass123
        vm_disk_size: '10G'
        vm_os_variant: centos8 # from `osinfo-query os`
        vm_ram_in_mb: 2048
        vm_vcpu: 2       
        vm_cloud_image_url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-ec2-8.2.2004-20200611.2.x86_64.qcow2
        vm_cloud_image_filename: centos_8_2.qcow2
 

    vmhost:
      hosts:
          localhost:
            ansible_connection: local # Should still work over regular ssh but untested
            ansible_host: 10.1.10.1 # needed to create macvtap link
            host_vm_storage_dir: "/storage/VM/images"
            base_images_dir: "/storage/VM/base_images"
            cloud_init_data_path: "/storage/VM/cloud_init_data"
            ansible_vms_group: "vms" # the host group defined in this inventory file that contains all the VMs to build
            host_macvlan_name: "host_br0"
            host_macvlan_subnet: 
              # The inner subnet where all VM's will reside. 
              # This is used to create a shortcut route on this VM host to allow for host->guest communication
              10.1.200.1/24 
            host_ethernet_interface: enp30s0
            host_vm_network_name: macvtap-net # libvirt network name for the VMs. Can be any name
            

