---
- name: Create macvlan bridge for host-to-guest communication
  block:
    - command: 
        cmd: nmcli con del {{ host_macvlan_name }}
      register: result
      failed_when: result.rc != 0 and "cannot delete unknown connection" not in result.stderr
    - command: nmcli con add type macvlan con-name {{ host_macvlan_name }} dev {{ host_ethernet_interface }} mode bridge tap no ifname {{ host_macvlan_name }}
    - command: nmcli con down {{ host_macvlan_name }}
    - command: nmcli con mod {{ host_macvlan_name }} ipv4.never-default true ipv4.method manual ipv4.addresses {{ ansible_host }}/32 ipv4.routes {{ host_macvlan_subnet }} ipv4.route-metric 50
    - command: nmcli con up {{ host_macvlan_name }} 
 

- name: Create vmnet xml file
  block:
    - tempfile:
        state: file
        suffix: temp_vmnet
      register: vmnet_file
    - template:
        src: vm_net.xml.j2
        dest: "{{ vmnet_file.path }}"

- name: import the vmnet xml
  block:
    - command: virsh net-define {{ vmnet_file.path }}
    - command: virsh net-autostart {{ host_vm_network_name }}
    - command: virsh net-destroy {{ host_vm_network_name }}
      register: result
      failed_when: result.rc != 0 and " is not active" not in result.stderr
    - command: virsh net-start {{ host_vm_network_name }}