---
- name: Install necessary packages
  yum:
    name: 
      - libvirt
      - virt-install
      - libguestfs-tools-c

- name: Ensure libvirt daemon is running
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Create necessary directories
  file:
    path:  "{{ item }}"
    state: directory
    group: kvm
    mode: '0775'
  with_items:
    - "{{ vmhost_vm_storage_dir }}"
    - "{{ vmhost_base_images_dir }}"
    - "{{ vmhost_cloud_init_storage_path }}"

- name: Create macvlan bridge for host-to-guest communication
  template:
    src: network-manager-macvlan.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/{{ vmhost_macvlan_name }}.nmconnection
    mode: '600' # from man NetworkManager.conf 'it will ignore files that are readable or writeable by any user or group other than root'
    owner: root
    group: root
  register: nm_macvlan_connection

- name: Reload Network Manager connection
  command: nmcli connection reload
  when: nm_macvlan_connection.changed == True

- name: Configure LibVirt Network
  import_tasks: setup_vmnet.yml

- name: Create/Provision VMs
  include_tasks: setup_vm.yml
  vars:
    vm_base_image_url: "{{ hostvars[vm_hostname]['vm_base_image_url'] }}"
    vm_base_image_filename: "{{ hostvars[vm_hostname]['vm_base_image_filename'] }}"
    vm_root_pass: "{{ hostvars[vm_hostname]['vm_root_pass'] }}"
    vm_root_ssh_auth_key: "{{ hostvars[vm_hostname]['vm_root_ssh_auth_key'] }}"
    vm_mac_address: "{{ hostvars[vm_hostname]['vm_mac_address'] }}"
    vm_ip_address: "{{ hostvars[vm_hostname]['ansible_host'] }}"
    vm_disk_size: "{{ hostvars[vm_hostname]['vm_disk_size'] }}"
    vm_vcpu_count: "{{ hostvars[vm_hostname]['vm_vcpu_count'] }}"
    vm_ram_in_mb: "{{ hostvars[vm_hostname]['vm_ram_in_mb'] }}"
    vm_os_variant: "{{ hostvars[vm_hostname]['vm_os_variant'] }}"
    vm_additional_disk_images:
      - "{{ vm_cloud_init_dir }}/user-data.img"
    vm_network_name: "{{ vmhost_network_name }}"
  with_items: "{{ groups[virtual_machines_ansible_group] }}"
  loop_control:
    loop_var: vm_hostname